version: '2'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - .:/var/www/
            - ./.docker/config/default.conf:/etc/nginx/conf.d/default.conf

